### ISSUE TITLE
bot update

### ISSUE THREAD

**Issue by TheZ3ro** [mayoral/telegrammer#12]
Is the bot updated with latest Bot API?

> September 18, 2015
> - Bots can now download files and media sent by users.
> - Added getFile and File.

https://core.telegram.org/bots/api-changelog

**Comment by mayoral** [comment]
Nope. The latest version supported is 2015-09-07.

As far as I can see on the docs we only have to implement a wrapper for the getFile method and add a File data type. I'll take a look into this this weekend.

**Comment by TheZ3ro** [comment]
Ok thanks :)

**Comment by mayoral** [comment]
Hi!

I've just released version 0.6.0 with support for get_file and the new File and Chat datatypes. Also updated the README to point to the latest version of the API supported (currently 2015-10-08).

**Comment by TheZ3ro** [comment]
Wonderful!
