### ISSUE TITLE
Need change in chat datatype attribute type

### ISSUE THREAD

**Issue by rkpasia** [mayoral/telegrammer#15]
> You can now pass a channel username (in the format @channelusername) in the place of chat_id in all methods (and instead of from_chat_id in forwardMessage). For this to work, the bot must be an administrator in the channel.

When I call the `send_message` method I need to insert the username of a channel in the `chat_id` field as it is supported from the latest telegram api.

I think you need to change the `id` attribute inside the `chat` datatype! From Integer -> String maybe?

Thanks a lot!!

**Comment by mayoral** [comment]
Thanks, Riccardo!

I've released version 0.6.1 adding support for `"@channel"` in the operations that have as parameter either `chat_id` or `from_chat_id`. I've also updated the docs.

**Comment by rkpasia** [comment]
Thanks a lot @mayoral :)
