### ISSUE TITLE
0.7.0 broken gem

### ISSUE THREAD

**Issue by markkuit** [mayoral/telegrammer#17]
Latest commits (aka version 0.7.0) have broken the gem due to wrong class inheritance.
Reporting this as an issue rather than making a pull request for a simple fix.

```
/usr/local/share/gems/gems/virtus-1.0.5/lib/virtus/const_missing_extensions.rb:14:in `const_missing': uninitialized constant Telegrammer::DataTypes::Update::InlineQuery (NameError)
    from /usr/local/share/gems/gems/telegrammer-0.7.0/lib/telegrammer/data_types/update.rb:13:in `<class:Update>'
    from /usr/local/share/gems/gems/telegrammer-0.7.0/lib/telegrammer/data_types/update.rb:10:in `<module:DataTypes>'
    from /usr/local/share/gems/gems/telegrammer-0.7.0/lib/telegrammer/data_types/update.rb:2:in `<module:Telegrammer>'
    from /usr/local/share/gems/gems/telegrammer-0.7.0/lib/telegrammer/data_types/update.rb:1:in `<top (required)>'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from telegrammer.rb:26:in `<main>'
```

**Comment by arturtr** [comment]
+1

**Comment by mayoral** [comment]
Hi @markkuit. I've just released version 0.7.1 fixing this order problem. I've also update the docs to reflect that now get_updates will return an update that can be a Message or a InlineQuery.

Can you take a look?

Thanks.

**Comment by markkuit** [comment]
Hi,

can confirm the classes are now properly loaded and .get_updates properly returns either Telegrammer::DataTypes::Message or Telegrammer::DataTypes::InlineQuery.

Thanks for the follow-up!

**Comment by TheZ3ro** [comment]
One more thing, @mayoral can you update Compliant API version in the readme? Thanks :smile:

**Comment by mayoral** [comment]
@TheZ3ro I've just seen that Telegram has made a minor update to the API, returning the chosen inline result in the updates. So my plan is to release this weekend a version 0.8.0 with these changes and the updated README :)

**Comment by mayoral** [comment]
These are the links I'm talking about:

https://core.telegram.org/bots/inline#collecting-feedback
https://core.telegram.org/bots/api-changelog#january-14-2016

I'll also add the newly released channel about bot news in the README:

https://telegram.me/BotNews

**Comment by TheZ3ro** [comment]
Very good :+1:

**Comment by mayoral** [comment]
Sorry for this delay... A lot of work lately :/

Version 0.8.0 released with these minor changes. API version supported is now 2016-01-20 (https://core.telegram.org/bots/api-changelog#january-20-2016).
