### ISSUE TITLE
Inline Methods

### ISSUE THREAD

**Issue by kennetham** [mayoral/telegrammer#19]
Hi I got an error while running this command

``` ruby
bot.get_updates do |message|
      if message.is_a?(Telegrammer::DataTypes::InlineQuery)
        inline_query = message.inline_query

        if inline_query
          results = [
              [1, 'First article', 'Very interesting text goes here.'],
              [2, 'Second article', 'Another interesting text here.']
          ].map do |arr|
            Telegrammer::DataTypes::InlineQueryResultArticle.new(
                id: arr[0],
                title: arr[1],
                input_message_content: Telegrammer::DataTypes::InputTextMessageContent.new(message_text: arr[2])
            )
          end

          bot.answer_inline_query(
              inline_query_id: "my-internal-query-id",
              results: results
          )
        end
      end
end
```

``` log
main.rb:597:in `block in <class:Main>': undefined method `inline_query' for #<Telegrammer::DataTypes::InlineQuery:0x007fb89cb22d78> (NoMethodError)...
```

**Comment by kennetham** [comment]
Resolved. Missed out something on my end.

**Comment by mayoral** [comment]
Cool!

Anyways I'm currently working on a big update regarding Bots API 2.0. There are a lot of new data types, lots of changes in some of the current ones, new methods, etc.

I was wondering what's the right version schema for a gem like this. I was thinking to bump version numbers to something like 2.x.y.z, where 2 is the API version supported, and x.y.z following the [semantic versioning](http://semver.org/). But maybe saying that this gem is on version "2 point something" I'm sending a wrong message, like if it was a stable version.

What do you think about it?

**Comment by kennetham** [comment]
I would suggest keeping the version close to your development rather than to Bots API versioning scheme. You are doing great with semantic versioning for your bot, and if the update is a major one, I suggest pushing it up to a 1.0.0 for your API, it's helpful for many others who use your API. It should help keep things neat than the confusion with Bots API. You are right that it would send a wrong message though.

Just my few cents worth. Hopefully it helps. :)

**Comment by mayoral** [comment]
Thanks for sharing your opinion, Kenneth!

My dilema is that since is so big and with some breaking changes, I need to do a big version bump. But, in the other side, I don't feel is ok to give it a 1.0.0 until I can have a good test suite.

Currently I haven't added tests since for me feels weird to add tests mocking Telegram responses only, and the datatypes can be considered as tested since they are plain Virtus objects.

**Comment by kennetham** [comment]
Although I agree with you that at the moment there isn't exactly a good test suite to justify a 1.0.0, however, I think this change itself would be quite a big difference to the previous set, since inline markups are now available.

I could spend some time to help you out. There's some great ideas to make this even better, especially if you replace it with some handler to handle the updates, would be great! :)

**Comment by mayoral** [comment]
Any help is always more than welcome :)

I've just sent you a mail with some details on how to contact me.

After we can release a version 1.0.0 I'll setup some more things, like a home page for the gem, mailing list, etc.
