### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by vasya555** [mayoral/telegrammer#20]
Hello!!!как можно утащить ник телеграмм у пользователя?

**Comment by mayoral** [comment]
Hi! Can you write in english, please?

**Comment by vasya555** [comment]
No.I'm Russia .

**Comment by mayoral** [comment]
Sorry, but I don't understand russian. Closing issue.

**Comment by vasya555** [comment]
Help scrounge userneim in telegramm

**Comment by vasya555** [comment]
Помогите утащить ник в телеграмм

**Comment by mayoral** [comment]
Based on a translation by Google Translate, what you are asking me is not related in any way with this ruby gem.

If you need support with Telegram, please go to https://telegram.org/support.
