### ISSUE TITLE
Telegram Bot Group Chat

### ISSUE THREAD

**Issue by kennetham** [mayoral/telegrammer#5]
Hi I tried to receive group chat messages and to send to group chats with the bot but when I added the bot into the group, the messages were not sent at all.

Please advise

**Comment by mayoral** [comment]
Did you change the privacy mode of the bot? By default all bots have set the privacy mode to enabled. 

You can get more info about this here https://core.telegram.org/bots#privacy-mode

**Comment by kennetham** [comment]
@mayoral Okay I think I did not change the bot privacy mode. So to be correct, I need to disable the privacy mode?
Also, how do I know the group chat ID?

To send a message in the group is it just 

``` ruby
bot = Telegrammer::Bot.new('[YOUR TELEGRAM TOKEN]')

bot.get_updates do |message|
  puts "In chat #{message.chat.id}, @#{message.from.username} said: #{message.text}"
  bot.send_message(chat_id: message.chat.id, text: "You said: #{message.text}")
end
```

Please advise if I need additional codes for group chats. Thank you

**Comment by mayoral** [comment]
Yes, you need to disable it using the BotFather.

On a `Message` object, the chat can be either a `User` or a `GroupChat` object. They both share an attribute called `id`, so you can always take the id using `message.chat.id`.

There is not additional code for group chats. They are just messages that your bot receive in `get_updates` (or via webhooks), like any other message. All the operations that sends anything (send_message, send_photo, etc) only need a chat_id. There is no distinction between group chats or user chats.

**Comment by kennetham** [comment]
I see. Cool. That helped! I was wondering why my bot wasn't listening or responding to the commands in a group chat.
