### ISSUE TITLE
Telegram stickers not sending

### ISSUE THREAD

**Issue by kennetham** [mayoral/telegrammer#6]
Please advise, I tried to push a sticker image with ".webp" or even normal sticker with ID, it didn't work.
What is the code that I am missing?

**Comment by mayoral** [comment]
Hi Kenneth.

I personally haven't tried to send a sticker, just implemented this operation in the same way I did the other `send_*`. But from tests in other `send_*` operations I saw that when a file format is not valid for them, they just return an empty message as a response, not an error.

In this case the only advice I can give you is to ask them directly on https://telegram.me/botsupport and share their answer about this issue.

**Comment by kennetham** [comment]
Cool sound great!

**Comment by mamantoha** [comment]
It works for me if send proper sticker file id.
For example:

``` ruby
sticker_file_id = 'BQADAgADNgADyIsGAAHg7uyYOZdcHAI'                                                                                                                                                                                   
bot.send_sticker(chat_id: message.chat.id, sticker: sticker_file_id)
```

**Comment by kennetham** [comment]
@mamantoha Can I ask how do you know the sticker_file_id? Where can I find them?

**Comment by mamantoha** [comment]
@kennetham 

I send a sticker to bot and watch the result in the console.

``` ruby
require 'telegrammer'

bot = Telegrammer::Bot.new('[YOUR TELEGRAM TOKEN]')

bot.get_updates do |message|
  if message.sticker
    puts "Sticker file_id: #{message.sticker.file_id}"
  else
    puts "No sticker"
  end
end
```

**Comment by kennetham** [comment]
@mamantoha THAT IS GENIUS! Thank you

**Comment by mayoral** [comment]
@kennetham did you finally talk to their support to know why it was failing when you sent the webp files?

**Comment by kennetham** [comment]
@mayoral Nope. nobody got back to me. I have yet to figure why .webp is not sending.

**Comment by mayoral** [comment]
Oh :(

Please keep us informed if you finally find a solution for this.

Thanks!

**Comment by kennetham** [comment]
Yup sure!

**Comment by kennetham** [comment]
By the way a few questions I have in mind. While waiting for support to get back, any idea how BotFather does the `/cancel` mechanism?

**Comment by mayoral** [comment]
@kennetham probably tracking each last command by a given chat id.

You can do this in a lot of different ways, each one with his pros and cons: A hash with chat_id as key an last command as value, a redis set using chat_id as key, records in a database...

**Comment by kennetham** [comment]
@mayoral hmm but how do you with the chat_id cancel the activity?

**Comment by mayoral** [comment]
You cannot think in terms of activities... You'll be receiving messages from hundreds of different chats in the same stream.

You have to track each chat id as a different session. And in each session, track the commands you are receiving, if needed.

If you receive `/help` you don't need to save the command, just send a message with help about your bot. If a user sends `/command1`, save somewhere that for chat id X your are in the first step of the command1 (if that command supports various steps, like they do in the Botfather to make more natural to execute).

The next message for that chat id have to be analyzed as the second step for command1, and so on, until the user sends you a `/cancel`. Then you can cancel internally that command session for that chat id.

You are the responsible to define and track the workflow of a conversation.
