### ISSUE TITLE
SetWebhook Enable notifications

### ISSUE THREAD

**Issue by kennetham** [mayoral/telegrammer#8]
@mayoral Do you have any examples on webhook?
https://core.telegram.org/bots#deep-linking

I am trying to create something like https://telegram.me/alertbot

From what I understand is webhook.

**Comment by mayoral** [comment]
You can take a look here: https://github.com/mayoral/telegrammer/wiki/Using-webhooks

Hope it helps. If you have any doubts using the gem, please ping me :)

**Comment by kennetham** [comment]
@mayoral thanks for replying. I am curious how the handle URL is derived? What should the URL be?

**Comment by mayoral** [comment]
You can use any route you want, as long as the route is a POST route. Also, that URL will not receive any csrf token, so you'll need to skip this check in your Rails app.

**Comment by kennetham** [comment]
Cool. I got to try it. Thank you!
